# Use uma imagem base do Python
FROM python:3.12

# Defina o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copie os arquivos necessários para o contêiner
COPY . /app

# Instale as dependências do Python
RUN pip install fastapi uvicorn pandas scikit-learn

# Exponha a porta que sua API FastAPI escuta
EXPOSE 8000

# Comando para iniciar o servidor Uvicorn para sua API
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
